### PR TITLE
Update test-infra dependency

### PR DESCRIPTION
**Pull request by nbarthwal**
Update the test-infra dependency in vendor using dep update

### CODE REVIEW

**Comment by adrcunha** [comment]
/retest won't work. If you check the logs, you'll see that a function is missing.

https://github.com/knative/build-templates/pull/102 must be approved/merged first, or this PR won't pass the presubmit tests.

**Comment by nbarthwal** [comment]
Let me ping Jason for 102 and then redo it.

**Comment by adrcunha** [comment]
You don't have to redo this PR.

**Comment by adrcunha** [comment]
@nbarthwal please solve the conflicts

**Comment by nbarthwal** [comment]
Closed as a new one is sent!

**Pull request closed without merging**
