### PR TITLE
Fix typo in readme

### PR DESCRIPTION
**Pull request by huoqifeng**
Signed-off-by: huoqifeng <huoqif@cn.ibm.com>

### CODE REVIEW

**Comment by huoqifeng** [comment]
CLA should be signed as corporate, set the signed email as primary email in this account just now.

**Comment by ImJasonH** [comment]
The failures are related to markdown lint errors which haven't always been enforced. If you want to fix them that's fine, otherwise I'll make the changes on your branch.

**Comment by huoqifeng** [comment]
@ImJasonH let me fix it. I'd like to use this PR to start my journal in knative, thanks for the review!

**Comment by huoqifeng** [comment]
@ImJasonH the lint err is fixed, may you help review again and merge it? I noticed there is a CLA warning but it's actually signed and can been found here: https://cla.developers.google.com/clas after login by any of my email registered in my account. still not figured out why..But I think which won't block your merging... thanks!

**Comment by huoqifeng** [comment]
@ImJasonH @mattmoor would you mind have a look at the PR? this is my first contribution to the project, I'm happy to continue my efforts once it's get merged.

**Pull request merged**
