### PR TITLE
ClusterBuildTemplate variations of each BuildTemplate file

### PR DESCRIPTION
**Pull request by drnic**
```
$ kubectl apply -f buildpack/buildpack-cluster.yaml
clusterbuildtemplate.build.knative.dev/buildpack created
$ kubectl apply -f buildpack/buildpack.yaml
buildtemplate.build.knative.dev/buildpack created
```

* [x] Includes `./hack/generate-cluster-templates.sh` to regenerate `*-cluster.yaml` files from the `kind: BuildTemplate` versions.
* [x] includes `test/build-buildpack-cluster.yaml`

### CODE REVIEW

**Comment by drnic** [comment]
Was there a reason to not merge this last year? Want me to rebase?

**Comment by vdemeester** [comment]
@drnic I don't think so cc @ImJasonH

**Comment by ImJasonH** [comment]
I'm not sure how I so thoroughly missed this PR! :astonished: 

I'm slightly opposed to having to maintain two copies of each build template going forward, it seems like a recipe for them getting out of sync in confusing and unobvious ways, or otherwise like a speed bump to avoid in every future PR that gets proposed.

Perhaps if there was a CI test that checked that they were identical, and a script that could be run to copy-and-update the `ClusterBuildTemplate` version, that would help a lot.

And in any case I think if we're going to invest in improving this catalog of build templates, we should consider making the same change instead of / in addition to the Tekton Task catalog at https://github.com/tektoncd/catalog.

Up to you if you want to move this forward, I don't feel strongly that we really need it. Maybe just a blurb somewhere that any namespaced `BuildTemplate` can also be installed as a `ClusterBuildTemplate` by changing the `kind`.

WDYT?

**Comment by drnic** [comment]
Ok, I'll close the issue for now. Someone/myself can reopen in future.

**Pull request closed without merging**
